x-common-variables: &global-vars
  TZ: "Europe/Moscow"

services:

  dictionary:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_FULL: "docker.io/library"
    container_name: dictionary
    environment:
      <<: *global-vars
    env_file:
      - .env
    restart : always
    command: /bin/bash -c "python3 main.py"
